### ISSUE TITLE
Overview window borked (https://issues.jalview.org/browse/JAL-4025)

### ISSUE THREAD

**Issue by jamesabbott** [jalview/jalview-js#14]
Well, maybe not borked so much as not made to work yet...

Selecting 'view' -> 'overview window' opens the overview window, but the alignment overview is not rendered. 

You can still use it to navigate the alignment, just can't see where you are going!

Screenshot attached...

![Screenshot 2022-06-28 at 22 13 07](https://user-images.githubusercontent.com/5315529/176289048-e1a90f2d-74ce-4f11-bb7b-00db5257bda1.png)

**Comment by jamesabbott** [comment]
Should have added:

#--Jalview Build Details--
#2022-06-01 11:57:07
BUILD_DATE=11:57:07 01 June 2022
INSTALLATION=Source git-commit:11c0c1e242 [releases/Release_2_11_2_Branch]
VERSION=TEST

**Comment by foreveremain** [comment]
Issue reported via https://issues.jalview.org/browse/JAL-4025

**Comment by foreveremain** [comment]
Issue only affects development builds of JalviewJS with SwingJS runtime later than 3.2.9
