### ISSUE TITLE
CSS position not defined in example html files

### ISSUE THREAD

**Issue by smoretti** [jalview/jalview-js#4]
Hi

The div element with the _System.out_ contains a CSS position style that is not defined in all example HTML files, as well as in the README.md file.
`<div style="*position:*left:900px;top:30px;width:600px;height:300px;">`

**Comment by smoretti** [comment]
Also to allow resizing of the div sysoutdiv helps a lot (*resize:both*) for debugging

**Comment by foreveremain** [comment]
pushed a fix - does this look right @smoretti ?

**Comment by smoretti** [comment]
Depends where you want to anchor the div but it looks right.
Just the resize:both should be in the *<div id="sysoutdiv"* css, not in the upper div
